// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjsrgwxtfqdrptzbitpq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhqc3Jnd3h0ZnFkcnB0emJpdHBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMzQ5MzcsImV4cCI6MjA2MDcxMDkzN30.T2V5_gpAJnahxwQX9r-1HCmjIEpTaQzLn7hiksqnbWo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);